/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * CarrinhoProduto
 */

public class CarrinhoProduto {
  @SerializedName("idCarrinho")
  private Integer idCarrinho = null;

  @SerializedName("carrinho")
  private Carrinho carrinho = null;

  @SerializedName("idProduto")
  private Integer idProduto = null;

  @SerializedName("produto")
  private Produto produto = null;

  @SerializedName("quantidade")
  private Double quantidade = null;

  public CarrinhoProduto idCarrinho(Integer idCarrinho) {
    this.idCarrinho = idCarrinho;
    return this;
  }

   /**
   * Get idCarrinho
   * @return idCarrinho
  **/
  public Integer getIdCarrinho() {
    return idCarrinho;
  }

  public void setIdCarrinho(Integer idCarrinho) {
    this.idCarrinho = idCarrinho;
  }

  public CarrinhoProduto carrinho(Carrinho carrinho) {
    this.carrinho = carrinho;
    return this;
  }

   /**
   * Get carrinho
   * @return carrinho
  **/
  public Carrinho getCarrinho() {
    return carrinho;
  }

  public void setCarrinho(Carrinho carrinho) {
    this.carrinho = carrinho;
  }

  public CarrinhoProduto idProduto(Integer idProduto) {
    this.idProduto = idProduto;
    return this;
  }

   /**
   * Get idProduto
   * @return idProduto
  **/
  public Integer getIdProduto() {
    return idProduto;
  }

  public void setIdProduto(Integer idProduto) {
    this.idProduto = idProduto;
  }

  public CarrinhoProduto produto(Produto produto) {
    this.produto = produto;
    return this;
  }

   /**
   * Get produto
   * @return produto
  **/
  public Produto getProduto() {
    return produto;
  }

  public void setProduto(Produto produto) {
    this.produto = produto;
  }

  public CarrinhoProduto quantidade(Double quantidade) {
    this.quantidade = quantidade;
    return this;
  }

   /**
   * Get quantidade
   * @return quantidade
  **/
  public Double getQuantidade() {
    return quantidade;
  }

  public void setQuantidade(Double quantidade) {
    this.quantidade = quantidade;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarrinhoProduto carrinhoProduto = (CarrinhoProduto) o;
    return Objects.equals(this.idCarrinho, carrinhoProduto.idCarrinho) &&
        Objects.equals(this.carrinho, carrinhoProduto.carrinho) &&
        Objects.equals(this.idProduto, carrinhoProduto.idProduto) &&
        Objects.equals(this.produto, carrinhoProduto.produto) &&
        Objects.equals(this.quantidade, carrinhoProduto.quantidade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCarrinho, carrinho, idProduto, produto, quantidade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarrinhoProduto {\n");
    
    sb.append("    idCarrinho: ").append(toIndentedString(idCarrinho)).append("\n");
    sb.append("    carrinho: ").append(toIndentedString(carrinho)).append("\n");
    sb.append("    idProduto: ").append(toIndentedString(idProduto)).append("\n");
    sb.append("    produto: ").append(toIndentedString(produto)).append("\n");
    sb.append("    quantidade: ").append(toIndentedString(quantidade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
