/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
/**
 * Carrinho
 */

public class Carrinho {
  @SerializedName("idCarrinho")
  private Integer idCarrinho = null;

  @SerializedName("produtosCarrinho")
  private List<CarrinhoProduto> produtosCarrinho = null;

  public Carrinho idCarrinho(Integer idCarrinho) {
    this.idCarrinho = idCarrinho;
    return this;
  }

   /**
   * Get idCarrinho
   * @return idCarrinho
  **/
  public Integer getIdCarrinho() {
    return idCarrinho;
  }

  public void setIdCarrinho(Integer idCarrinho) {
    this.idCarrinho = idCarrinho;
  }

  public Carrinho produtosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
    return this;
  }

  public Carrinho addProdutosCarrinhoItem(CarrinhoProduto produtosCarrinhoItem) {
    if (this.produtosCarrinho == null) {
      this.produtosCarrinho = new ArrayList<CarrinhoProduto>();
    }
    this.produtosCarrinho.add(produtosCarrinhoItem);
    return this;
  }

   /**
   * Get produtosCarrinho
   * @return produtosCarrinho
  **/
  public List<CarrinhoProduto> getProdutosCarrinho() {
    return produtosCarrinho;
  }

  public void setProdutosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Carrinho carrinho = (Carrinho) o;
    return Objects.equals(this.idCarrinho, carrinho.idCarrinho) &&
        Objects.equals(this.produtosCarrinho, carrinho.produtosCarrinho);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCarrinho, produtosCarrinho);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Carrinho {\n");
    
    sb.append("    idCarrinho: ").append(toIndentedString(idCarrinho)).append("\n");
    sb.append("    produtosCarrinho: ").append(toIndentedString(produtosCarrinho)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
