/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Date;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
/**
 * Compra
 */

public class Compra {
  @SerializedName("idCompra")
  private Integer idCompra = null;

  @SerializedName("idVendedor")
  private Integer idVendedor = null;

  @SerializedName("data")
  private Date data = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("valorTotal")
  private Double valorTotal = null;

  @SerializedName("produtosCarrinho")
  private List<CarrinhoProduto> produtosCarrinho = null;

  @SerializedName("produtosCompra")
  private List<CompraProduto> produtosCompra = null;

  public Compra idCompra(Integer idCompra) {
    this.idCompra = idCompra;
    return this;
  }

   /**
   * Get idCompra
   * @return idCompra
  **/
  public Integer getIdCompra() {
    return idCompra;
  }

  public void setIdCompra(Integer idCompra) {
    this.idCompra = idCompra;
  }

  public Compra idVendedor(Integer idVendedor) {
    this.idVendedor = idVendedor;
    return this;
  }

   /**
   * Get idVendedor
   * @return idVendedor
  **/
  public Integer getIdVendedor() {
    return idVendedor;
  }

  public void setIdVendedor(Integer idVendedor) {
    this.idVendedor = idVendedor;
  }

  public Compra data(Date data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  public Date getData() {
    return data;
  }

  public void setData(Date data) {
    this.data = data;
  }

  public Compra status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Compra valorTotal(Double valorTotal) {
    this.valorTotal = valorTotal;
    return this;
  }

   /**
   * Get valorTotal
   * @return valorTotal
  **/
  public Double getValorTotal() {
    return valorTotal;
  }

  public void setValorTotal(Double valorTotal) {
    this.valorTotal = valorTotal;
  }

  public Compra produtosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
    return this;
  }

  public Compra addProdutosCarrinhoItem(CarrinhoProduto produtosCarrinhoItem) {
    if (this.produtosCarrinho == null) {
      this.produtosCarrinho = new ArrayList<CarrinhoProduto>();
    }
    this.produtosCarrinho.add(produtosCarrinhoItem);
    return this;
  }

   /**
   * Get produtosCarrinho
   * @return produtosCarrinho
  **/
  public List<CarrinhoProduto> getProdutosCarrinho() {
    return produtosCarrinho;
  }

  public void setProdutosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
  }

  public Compra produtosCompra(List<CompraProduto> produtosCompra) {
    this.produtosCompra = produtosCompra;
    return this;
  }

  public Compra addProdutosCompraItem(CompraProduto produtosCompraItem) {
    if (this.produtosCompra == null) {
      this.produtosCompra = new ArrayList<CompraProduto>();
    }
    this.produtosCompra.add(produtosCompraItem);
    return this;
  }

   /**
   * Get produtosCompra
   * @return produtosCompra
  **/
  public List<CompraProduto> getProdutosCompra() {
    return produtosCompra;
  }

  public void setProdutosCompra(List<CompraProduto> produtosCompra) {
    this.produtosCompra = produtosCompra;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Compra compra = (Compra) o;
    return Objects.equals(this.idCompra, compra.idCompra) &&
        Objects.equals(this.idVendedor, compra.idVendedor) &&
        Objects.equals(this.data, compra.data) &&
        Objects.equals(this.status, compra.status) &&
        Objects.equals(this.valorTotal, compra.valorTotal) &&
        Objects.equals(this.produtosCarrinho, compra.produtosCarrinho) &&
        Objects.equals(this.produtosCompra, compra.produtosCompra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idCompra, idVendedor, data, status, valorTotal, produtosCarrinho, produtosCompra);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Compra {\n");
    
    sb.append("    idCompra: ").append(toIndentedString(idCompra)).append("\n");
    sb.append("    idVendedor: ").append(toIndentedString(idVendedor)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    valorTotal: ").append(toIndentedString(valorTotal)).append("\n");
    sb.append("    produtosCarrinho: ").append(toIndentedString(produtosCarrinho)).append("\n");
    sb.append("    produtosCompra: ").append(toIndentedString(produtosCompra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
