/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * CompraProduto
 */

public class CompraProduto {
  @SerializedName("produto")
  private Produto produto = null;

  @SerializedName("idProduto")
  private Integer idProduto = null;

  @SerializedName("compra")
  private Compra compra = null;

  @SerializedName("idCompra")
  private Integer idCompra = null;

  @SerializedName("quantidade")
  private Double quantidade = null;

  public CompraProduto produto(Produto produto) {
    this.produto = produto;
    return this;
  }

   /**
   * Get produto
   * @return produto
  **/
  public Produto getProduto() {
    return produto;
  }

  public void setProduto(Produto produto) {
    this.produto = produto;
  }

  public CompraProduto idProduto(Integer idProduto) {
    this.idProduto = idProduto;
    return this;
  }

   /**
   * Get idProduto
   * @return idProduto
  **/
  public Integer getIdProduto() {
    return idProduto;
  }

  public void setIdProduto(Integer idProduto) {
    this.idProduto = idProduto;
  }

  public CompraProduto compra(Compra compra) {
    this.compra = compra;
    return this;
  }

   /**
   * Get compra
   * @return compra
  **/
  public Compra getCompra() {
    return compra;
  }

  public void setCompra(Compra compra) {
    this.compra = compra;
  }

  public CompraProduto idCompra(Integer idCompra) {
    this.idCompra = idCompra;
    return this;
  }

   /**
   * Get idCompra
   * @return idCompra
  **/
  public Integer getIdCompra() {
    return idCompra;
  }

  public void setIdCompra(Integer idCompra) {
    this.idCompra = idCompra;
  }

  public CompraProduto quantidade(Double quantidade) {
    this.quantidade = quantidade;
    return this;
  }

   /**
   * Get quantidade
   * @return quantidade
  **/
  public Double getQuantidade() {
    return quantidade;
  }

  public void setQuantidade(Double quantidade) {
    this.quantidade = quantidade;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompraProduto compraProduto = (CompraProduto) o;
    return Objects.equals(this.produto, compraProduto.produto) &&
        Objects.equals(this.idProduto, compraProduto.idProduto) &&
        Objects.equals(this.compra, compraProduto.compra) &&
        Objects.equals(this.idCompra, compraProduto.idCompra) &&
        Objects.equals(this.quantidade, compraProduto.quantidade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(produto, idProduto, compra, idCompra, quantidade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompraProduto {\n");
    
    sb.append("    produto: ").append(toIndentedString(produto)).append("\n");
    sb.append("    idProduto: ").append(toIndentedString(idProduto)).append("\n");
    sb.append("    compra: ").append(toIndentedString(compra)).append("\n");
    sb.append("    idCompra: ").append(toIndentedString(idCompra)).append("\n");
    sb.append("    quantidade: ").append(toIndentedString(quantidade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
