/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Email
 */

public class Email {
  @SerializedName("idEmail")
  private Integer idEmail = null;

  @SerializedName("enderecoEmail")
  private String enderecoEmail = null;

  public Email idEmail(Integer idEmail) {
    this.idEmail = idEmail;
    return this;
  }

   /**
   * Get idEmail
   * @return idEmail
  **/
  public Integer getIdEmail() {
    return idEmail;
  }

  public void setIdEmail(Integer idEmail) {
    this.idEmail = idEmail;
  }

  public Email enderecoEmail(String enderecoEmail) {
    this.enderecoEmail = enderecoEmail;
    return this;
  }

   /**
   * Get enderecoEmail
   * @return enderecoEmail
  **/
  public String getEnderecoEmail() {
    return enderecoEmail;
  }

  public void setEnderecoEmail(String enderecoEmail) {
    this.enderecoEmail = enderecoEmail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Email email = (Email) o;
    return Objects.equals(this.idEmail, email.idEmail) &&
        Objects.equals(this.enderecoEmail, email.enderecoEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idEmail, enderecoEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Email {\n");
    
    sb.append("    idEmail: ").append(toIndentedString(idEmail)).append("\n");
    sb.append("    enderecoEmail: ").append(toIndentedString(enderecoEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
