/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
/**
 * Produto
 */

public class Produto {
  @SerializedName("idProduto")
  private Integer idProduto = null;

  @SerializedName("titulo")
  private String titulo = null;

  @SerializedName("descricao")
  private String descricao = null;

  @SerializedName("preco")
  private Double preco = null;

  @SerializedName("qtdEstoque")
  private Integer qtdEstoque = null;

  @SerializedName("desconto")
  private Double desconto = null;

  @SerializedName("produtosCarrinho")
  private List<CarrinhoProduto> produtosCarrinho = null;

  @SerializedName("produtosCompra")
  private List<CompraProduto> produtosCompra = null;

  public Produto idProduto(Integer idProduto) {
    this.idProduto = idProduto;
    return this;
  }

   /**
   * Get idProduto
   * @return idProduto
  **/
  public Integer getIdProduto() {
    return idProduto;
  }

  public void setIdProduto(Integer idProduto) {
    this.idProduto = idProduto;
  }

  public Produto titulo(String titulo) {
    this.titulo = titulo;
    return this;
  }

   /**
   * Get titulo
   * @return titulo
  **/
  public String getTitulo() {
    return titulo;
  }

  public void setTitulo(String titulo) {
    this.titulo = titulo;
  }

  public Produto descricao(String descricao) {
    this.descricao = descricao;
    return this;
  }

   /**
   * Get descricao
   * @return descricao
  **/
  public String getDescricao() {
    return descricao;
  }

  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

  public Produto preco(Double preco) {
    this.preco = preco;
    return this;
  }

   /**
   * Get preco
   * @return preco
  **/
  public Double getPreco() {
    return preco;
  }

  public void setPreco(Double preco) {
    this.preco = preco;
  }

  public Produto qtdEstoque(Integer qtdEstoque) {
    this.qtdEstoque = qtdEstoque;
    return this;
  }

   /**
   * Get qtdEstoque
   * @return qtdEstoque
  **/
  public Integer getQtdEstoque() {
    return qtdEstoque;
  }

  public void setQtdEstoque(Integer qtdEstoque) {
    this.qtdEstoque = qtdEstoque;
  }

  public Produto desconto(Double desconto) {
    this.desconto = desconto;
    return this;
  }

   /**
   * Get desconto
   * @return desconto
  **/
  public Double getDesconto() {
    return desconto;
  }

  public void setDesconto(Double desconto) {
    this.desconto = desconto;
  }

  public Produto produtosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
    return this;
  }

  public Produto addProdutosCarrinhoItem(CarrinhoProduto produtosCarrinhoItem) {
    if (this.produtosCarrinho == null) {
      this.produtosCarrinho = new ArrayList<CarrinhoProduto>();
    }
    this.produtosCarrinho.add(produtosCarrinhoItem);
    return this;
  }

   /**
   * Get produtosCarrinho
   * @return produtosCarrinho
  **/
  public List<CarrinhoProduto> getProdutosCarrinho() {
    return produtosCarrinho;
  }

  public void setProdutosCarrinho(List<CarrinhoProduto> produtosCarrinho) {
    this.produtosCarrinho = produtosCarrinho;
  }

  public Produto produtosCompra(List<CompraProduto> produtosCompra) {
    this.produtosCompra = produtosCompra;
    return this;
  }

  public Produto addProdutosCompraItem(CompraProduto produtosCompraItem) {
    if (this.produtosCompra == null) {
      this.produtosCompra = new ArrayList<CompraProduto>();
    }
    this.produtosCompra.add(produtosCompraItem);
    return this;
  }

   /**
   * Get produtosCompra
   * @return produtosCompra
  **/
  public List<CompraProduto> getProdutosCompra() {
    return produtosCompra;
  }

  public void setProdutosCompra(List<CompraProduto> produtosCompra) {
    this.produtosCompra = produtosCompra;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Produto produto = (Produto) o;
    return Objects.equals(this.idProduto, produto.idProduto) &&
        Objects.equals(this.titulo, produto.titulo) &&
        Objects.equals(this.descricao, produto.descricao) &&
        Objects.equals(this.preco, produto.preco) &&
        Objects.equals(this.qtdEstoque, produto.qtdEstoque) &&
        Objects.equals(this.desconto, produto.desconto) &&
        Objects.equals(this.produtosCarrinho, produto.produtosCarrinho) &&
        Objects.equals(this.produtosCompra, produto.produtosCompra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idProduto, titulo, descricao, preco, qtdEstoque, desconto, produtosCarrinho, produtosCompra);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Produto {\n");
    
    sb.append("    idProduto: ").append(toIndentedString(idProduto)).append("\n");
    sb.append("    titulo: ").append(toIndentedString(titulo)).append("\n");
    sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
    sb.append("    preco: ").append(toIndentedString(preco)).append("\n");
    sb.append("    qtdEstoque: ").append(toIndentedString(qtdEstoque)).append("\n");
    sb.append("    desconto: ").append(toIndentedString(desconto)).append("\n");
    sb.append("    produtosCarrinho: ").append(toIndentedString(produtosCarrinho)).append("\n");
    sb.append("    produtosCompra: ").append(toIndentedString(produtosCompra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
