/*
 * etech-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.etech.etechmobile.entidades;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Telefone
 */

public class Telefone {
  @SerializedName("idTelefone")
  private Integer idTelefone = null;

  @SerializedName("ddd")
  private Integer ddd = null;

  @SerializedName("numero")
  private Integer numero = null;

  public Telefone idTelefone(Integer idTelefone) {
    this.idTelefone = idTelefone;
    return this;
  }

   /**
   * Get idTelefone
   * @return idTelefone
  **/
  public Integer getIdTelefone() {
    return idTelefone;
  }

  public void setIdTelefone(Integer idTelefone) {
    this.idTelefone = idTelefone;
  }

  public Telefone ddd(Integer ddd) {
    this.ddd = ddd;
    return this;
  }

   /**
   * Get ddd
   * minimum: 11
   * maximum: 99
   * @return ddd
  **/
  public Integer getDdd() {
    return ddd;
  }

  public void setDdd(Integer ddd) {
    this.ddd = ddd;
  }

  public Telefone numero(Integer numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Get numero
   * minimum: 11111111
   * maximum: 999999999
   * @return numero
  **/
  public Integer getNumero() {
    return numero;
  }

  public void setNumero(Integer numero) {
    this.numero = numero;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Telefone telefone = (Telefone) o;
    return Objects.equals(this.idTelefone, telefone.idTelefone) &&
        Objects.equals(this.ddd, telefone.ddd) &&
        Objects.equals(this.numero, telefone.numero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idTelefone, ddd, numero);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Telefone {\n");
    
    sb.append("    idTelefone: ").append(toIndentedString(idTelefone)).append("\n");
    sb.append("    ddd: ").append(toIndentedString(ddd)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
